architect: true

watch-files: true
max-chat-history-tokens: 32768
restore-chat-history: false
read:
  - "README.md"
  - "caf_gpt/settings/README.md"
  - "core/README.md"
  - "pacenote_foo/README.md"
  - "policy_foo/README.md"

# file:

auto-commits: false
attribute-commit-message-author: true
auto-lint: true
lint-cmd: 
  - "lint"

map-tokens: 2048
map-refresh: always

editor: neovim