architect: true

watch-files: true
max-chat-history-tokens: 32768
restore-chat-history: false
read:
  - "README.md"
  - "core/README.md"
  - "pacenote_foo/README.md"
  - "policy_foo/README.md"
  - "caf_gpt/settings/base.py"
  - "manage.py"

# file:

auto-commits: false
attribute-commit-message-author: true
auto-lint: true
lint-cmd: 
  - "autopep8 --in-place --recursive --aggressive --aggressive --max-line-length 150 . && flake8"

map-tokens: 2048
map-refresh: always

editor: neovim