architect: true

watch-files: true
max-chat-history-tokens: 32768
restore-chat-history: false
read:
  - "caf_gpt/settings.py"
  - "manage.py"
# file:

auto-commits: false
attribute-commit-message-author: true
auto-lint: true
lint-cmd: 
  - "npm run lint"

map-tokens: 2048
map-refresh: always

editor: neovim