architect: true

watch-files: true
max-chat-history-tokens: 32768
restore-chat-history: false
read:
  - README.md
  - rewrite.md
  - .env.example

file:
  - src/main.py
  - src/config.py
  - src/app_logging.py
  - src/llm_interface.py

auto-commits: false
attribute-commit-message-author: true
auto-lint: true
# lint-cmd: 
#   - "autopep8 --in-place --recursive --aggressive --aggressive --max-line-length 200 . && flake8"

map-tokens: 2048
map-refresh: always

editor: neovim